// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Feed = __t.object("Feed", {
  id: __t.u64(),
  kind: __t.string(),
  text: __t.string(),
  createdAt: __t.timestamp(),
});
export type Feed = __Infer<typeof Feed>;

export const Note = __t.object("Note", {
  id: __t.u64(),
  encounterId: __t.string(),
  author: __t.string(),
  text: __t.string(),
  createdAt: __t.timestamp(),
});
export type Note = __Infer<typeof Note>;

export const Presence = __t.object("Presence", {
  connectionId: __t.connectionId(),
  identity: __t.identity(),
  displayName: __t.string(),
  lastSeen: __t.timestamp(),
});
export type Presence = __Infer<typeof Presence>;

export const ThreatStatus = __t.object("ThreatStatus", {
  encounterId: __t.string(),
  status: __t.string(),
  setBy: __t.string(),
  updatedAt: __t.timestamp(),
});
export type ThreatStatus = __Infer<typeof ThreatStatus>;

